package com.api.util;

public interface WEBConstants
{

	int THREE_NUMB = 3;
	int FOUR_NUMB = 4;
    int PAGING_BLOCK_SIZE = 15;
    int IN = 0;
    int OUT = 1;
    int INOUT = 2;
    int SUCCESS = 1;
	int FAIL = 0;
	String BACK_SLASH ="/";
	String NULL ="";
	String YES ="Y";
	String NO ="N";
	String ACTIVE ="A";
	String  INACTIVE ="I";
    String  SOAP_SUCCESS ="SUCCESS";
    String  SOAP_FAULT ="FAULT";
    String  SOAP_DELETION_FAILURE = "FAILED TO DELETE";
    String  REST_RESPONSE_ACKNOWLEDGEMENT ="PLEASE FIND RESPONSE AGAINST RESPECTIVE ITEMS";
    String  NO_DATA_FOUND ="NO DATA FOUND";
    String  SOAP_INSERTED_SUCCESS="SUCCESSFULLY INSERTED";
    String  SOAP_INSERTED_FAILURE="FAILED TO INSERT";
    String  SOAP_UPDATED_SUCCESS="SUCCESSFULLY UPDATED";
    String  SOAP_UPDATED_FAILURE="FAILED TO UPDATE";
    String  SESSION_ID_MATCHED="SUCCESSFUL LOGIN";
    String  SESSION_ID_MISMATCH="INVALID SESSION!PLEASE LOGIN AGAIN";
    String  SESSION_ID_INVALID="INVALID";
    String  SESSION_ID_EXPIRED="SESSION_EXPIRED";
    String  DML_OPERATION_CREATE ="C";
    String  DML_OPERATION_UPDATE ="U";
    String  DML_OPERATION_DELETE ="X";
    String  DML_OPERATION_READ ="R";
    String  DML_OPERATION_READALL ="A";
    String  EXCEPTION_OCCURED="APPLICATION ERROR, PLEASE CHECK WITH ADMINISTRATOR FOR FURTHER ACTION";
    String  WRONG_OPERATION="SORRY!THIS OPERATION CANNOT BE PERFORMED.PLEASE CONTACT THE ADMINSTRATOR";
    String  NOT_ALLOWED="notallowed";
    String  SYNC_YES="SYNC_YES"; 
    String  OK = "OK";
    String  ALREADY = "ALREADY";
    String  FAILED = "FAIL";
    String  ERROR = "ERROR";
    String  ALREADY_DOWNLOADED = "ALREADY_DOWNLOADED";
    String  INVALID="INVALID";
    String INVALID_DATA="INVALID INPUT";
    String  NOT_AUTHORIZED ="NOT AN AUTHORIZED USER";
    String  XML_MARSHEL_MAP_KEY = "XML_MARSHEL_MAP_KEY"; 
    String SESSIONID = "session-id";
    String ASSET_USER_ID = "user-id";
    String DEVICE_ID = "device-id";
    String OPERATION_FLAG = "operation-flag";
    String USER_AGENT = "user-agent";
    String HOST_SERVER = "host";
    String RANDOM_SESSION_ID = "random-session-id";
    String HEADER_LOCATION = "Location";
    String HEADER_RESPONSE_TIME_MILLS = "response-time-milliseconds";
    String HEADER_RESPONSE_TIME_NANO = "response-time-nanoseconds";
    String HEADER_RESPONSE_CODE = "response-code";
    String HEADER_NETWORK_CODE = "network-code";
    String HEADER_REQUEST_ID = "request-id";
    String HEADER_UNIQUE_REQUEST_ID = "unique-request";
    String ACCEPTABLE_HEADER_TYPE_JSON = "Accept=application/json";
    String ACCEPTABLE_HEADER_TYPE_XML = "Accept=application/xml";
    String ACCEPTABLE_HEADER_TYPE_JSON_OR_XML = "Accept=application/xml, application/json";
}